{{ $count := (.Values.pvcCount | int) }}
{{- range untilStep 0 $count 1 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$.Values.guid}}-{{.}}-pvc
  ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Pod
      name: {{$.Values.guid}}
      uid: {{$.Values.pod_uid}}
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}